application: randsimpsons
version: 1
runtime: php
api_version: 1

handlers:
- url: /simple_html_dom.php
  script: simple_html_dom.php

- url: /scrapeSimpsons.php
  script: scrapeSimpsons.php

- url: /.*
  script: index.php
